Auto<-read.csv("Auto.csv",header=T,na.strings = "?")
Auto
dim(Auto)
fix(Auto)
dim(Auto)
Auto=na.omit(Auto)
Auto
dim(Auto)
summary(Auto)
attach(Auto)
range(mpg)
range(cylinders)
range(displacement)
range(weight)
range(acceleration)
range(year)
range(horsepower)
sd(horsepower)
mean(cylinders)
mean(displacement)
mean(weight)
mean(acceleration)
mean(year)
mean(origin)
sd(horsepower)
sd(cylinders)
sd(displacement)
sd(weight)
sd(acceleration)
sd(year)
sd(origin)
Dela<-Auto[10:85,]
Dela
?apply
apply(Dela[-c(10:85),1:8],2,range)
apply(Dela[-c(10:85),1:8],2,mean)
apply(Dela[-c(10:85),1:8],2,sd)
plot(Auto)
plot(cylinders, mpg, col=1:2,xlab = "cylinders",ylab = "mpg",main = "A plot of cylinders against mpg")
abline(acceleration, weight, col=3:5,xlab = "acceleration",ylab = "weight",main = "A plot of acceleration against weight")
plot(origin,year,col=8:10,xlab = "origin",ylab = "year",main = "A plot of origin against year")
(Auto)
boxplot(weight)
plot(mpg,acceleration,col=1:5,xlab = "mpg",ylab = "acceleration",main = "A graph to compare mpg and acceleration")
plot(mpg,horsepower,col=1:5,xlab = "mpg",ylab = "horsepower",main = "A graph to compare mpg and horsepower")
plot(mpg,year,col=1:5,xlab = "mpg",ylab = "year",main = "A graph to compare mpg and year")
plot(mpg,origin,col=1:5,xlab = "mpg",ylab = "origin",main = "A graph to compare mpg and origin")
